### ISSUE TITLE
Add to HACS

### ISSUE THREAD

**Issue by codeclinic** [Sennevds/system_sensors#10]
Have you considered adding this to HACS? It'll make the project more visible and greatly simplify the installation since HACS automates that.

**Comment by Sennevds** [comment]
I will check what I need to change to add it to HACS

**Comment by codeclinic** [comment]
That'd be great. HACS also makes keeping scripts up to date, really easy.

**Comment by codeclinic** [comment]
Likewise, you might want to consider adding this to pypi.org as that also makes things easy to install and keep updated.

Thanks.

**Comment by Sennevds** [comment]
Yeah I thought about it and I don't think it makes sense to add it to HACS because it's for monitoring external RPI's for the pi running Hass you can use https://www.home-assistant.io/integrations/systemmonitor/ which does basically the same.

**Comment by codeclinic** [comment]
But the info is still displayed in Home Assistant. So its just as valid a plugin on HACS as any other. It'd make installing /updating /uninstalling so much easier plus it makes it far more visible to HA users regardless of which platform HA is running on.

**Comment by Sennevds** [comment]
Yeah it's displayed in hass if you configure it. The only thing you add to hass is the UI and you need to do that yourself. I could add the python script to HACS but there is a internal component in home assistant that does the same as the thing I wrote so it wouldn't make sense to add it. 

This script it's purpose is to replicate the internal component but on remote PI's. Adding it to pypi makes much more sense.

**Comment by codeclinic** [comment]
To be honest I don't really get your logic for not including it, but I appreciate that it's your project to maintain the way that works best for you.

**Comment by codeclinic** [comment]
Ah, I just realised that I might have been a bit dumb with this. This is supposed to be installed on the remote device isn't it?

**Comment by codeclinic** [comment]
Pypi.org would definitely be the best place for this.
