### ISSUE TITLE
Unable to install on Raspbian Lite Buster

### ISSUE THREAD

**Issue by codeclinic** [Sennevds/system_sensors#11]
When I run `python3 system_sensors.py` I get this output and installation fails. I did install the required packages via requirements.txt. I also has MQTT already installed prior to this:

```
Traceback (most recent call last):
  File "src/system_sensors.py", line 108, in <module>
    client.connect(broker_url, broker_port)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/paho/mqtt/client.py", line 838, in connect
    self.connect_async(host, port, keepalive, bind_address)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/paho/mqtt/client.py", line 893, in connect_async
    raise ValueError('Invalid host.')
ValueError: Invalid host.
```

**Comment by Sennevds** [comment]
Did you change following 2 lines in the script:
```python
broker_url = ""#MQTT server IP
broker_port = 1883 #MQTT server port
```

**Comment by codeclinic** [comment]
> 
> 
> Did you change following 2 lines in the script:
> 
> ```python
> broker_url = ""#MQTT server IP
> broker_port = 1883 #MQTT server port
> ```

I just realised that I'd missed that part. However, I've since updated the MQTT settings but when I run `python3 system_sensors.py` it just hangs the system even though i'm in the correct directory for those files.

Any ideas why that might be?

**Comment by codeclinic** [comment]
Oh Damn! it was late and I was clearly tired and evidently left my brain in a dark cupboard. I've got it workin, despite my own stupidity.
