### ISSUE TITLE
make it work on different HW than rbpi

### ISSUE THREAD

**Issue by mariomare22** [Sennevds/system_sensors#111]
Hello!
Is it possible to make system_sensors compatible with amd64 running Ubuntu server?
I have tried to execute it but it's not working

Thanks, 

M.

**Comment by Sennevds** [comment]
It already works on different hardware. I have it running on a proxmox server. Did you get any error?

**Comment by mariomare22** [comment]
it works now I had a typo \t in the settings.yaml
