### ISSUE TITLE
OS_DATA gives: list index out of range

### ISSUE THREAD

**Issue by Andoramb** [Sennevds/system_sensors#112]
Hi,
With the refractor of the code, a bug was introduced, when getting the OS_DATA. At line 31 [_sensors.py_](https://github.com/Sennevds/system_sensors/blob/ec20be84399c14963572a106a3325b954f12e728/src/sensors.py#L31):
`OS_DATA[row[0]] = row[1].strip('"')`

My /etc/os-release has an empty row somewhere in the middle (running on a Vero4k+)

If I delete the empty row manually, the script executes correctly :)

Thanks

**Comment by Sennevds** [comment]
Could you check with the latest master version?

**Comment by Andoramb** [comment]
Yes, updated and works great :)
Thank you
