### ISSUE TITLE
HA entities Unavailable

### ISSUE THREAD

**Issue by Andoramb** [Sennevds/system_sensors#113]
Sorry to create another one, Just wanted to understand where I could look for debugging:
What I get on the output is:
```Oct 15 11:00:46 osmc systemd[1]: Started System Sensor service.
Oct 15 11:00:47 osmc python3.8[22810]: Unable to import apt package. Available updates will not be shown.
Oct 15 11:00:47 osmc python3.8[22810]: send config message
Oct 15 11:00:47 osmc python3.8[22810]: something whent wrong
Oct 15 11:00:47 osmc python3.8[22810]: Connected to broker
```

I'm running the latest commit;
Using a Vero4k+ (it was working previously)
My settings.yaml file looks correct (indent fixed + works on a PI)

A previous apt-related issue was solved, but as I saw in System_sensors.py, if the apt package cannot be opened, it's not a big deal (not using it anyway).

However this may be related to [send_config_message(mqttClient)](https://github.com/Sennevds/system_sensors/blob/ec20be84399c14963572a106a3325b954f12e728/src/system_sensors.py#L197)

Do you have any ideas where could I look?
Thanks :)

**Comment by Sennevds** [comment]
Could you try the latest master version?

**Comment by Andoramb** [comment]
Yes, looking good!
Because I'm on NUC, I still see
```
Unable to import rpi_bad_power library, or is incompatible on host architecture. Power supply info will not be shown.
Unable to import apt package. Available updates will not be shown.
```

But that's not relevant here.
Thanks!
