### ISSUE TITLE
net_rx is always 0.0

### ISSUE THREAD

**Issue by mcrodrig** [Sennevds/system_sensors#120]
Hi,

I noticed that net_rx is always 0.0 although I have data going through the net.

I'm running ubuntu 20.04 on raspberry pi 4b 8gb.

My configuration is as follows:
`sensors:`
`  temperature: true`
`  clock_speed: true`
`  disk_use: true`
`  memory_use: true`
`  cpu_usage: true`
`  load_1m: true`
`  load_5m: true`
`  load_15m: true`
`  net_tx: true`
`  net_rx: true`
`  swap_usage: true`
`  power_status: true`
`  last_boot: true`
`  hostname: true`
`  host_ip: true`
`  host_os: true`
`  host_arch: true`
`  last_message: true`
`  updates: true`
 ` wifi_strength: false`
`  wifi_ssid: false`

Is there anything wrong?

Thanks in advance

**Comment by mcrodrig** [comment]
Found the error. When doing get_net_data(1) the values from psutil.net_io_counters() are the same as they were in the get_net_data(0) and then 
`net_data = (net_data, (current_net_data[1] - old_net_data[1]) / (current_time - previous_time) * 8 / 1024)`
is 0

This is the first time I do python and don't feel like creating a PR, but here is my changed code 
`def get_net_data(arg):
    global old_net_data
    global previous_time
    global net_data

    if arg == 0:
        current_net_data = psutil.net_io_counters()
        current_time = time.time()
        if current_time == previous_time:
            current_time += 1
        net_data = (current_net_data[0] - old_net_data[0]) / (current_time - previous_time) * 8 / 1024
        net_data = (net_data, (current_net_data[1] - old_net_data[1]) / (current_time - previous_time) * 8 / 1024)
        previous_time = current_time
        old_net_data = current_net_data
        net_data = ['%.2f' % net_data[0], '%.2f' % net_data[1]]

    return net_data[arg]
`

**Comment by emigrating** [comment]
I'm seeing the same behavior. It seems like it happens because PSUtil is being run twich in quick succession to get bytes out/in. I solved it by adding a time.sleep(2) between the two calls, but it''s far from ideal. I reckon it'd be better to run it once and return both values at once.
