### ISSUE TITLE
Under power value

### ISSUE THREAD

**Issue by Kobiash** [Sennevds/system_sensors#126]
With the latest HA the value of the "under_power" is unknown.
![image](https://user-images.githubusercontent.com/64246045/152683907-b1ae1b11-afdd-4865-a7e2-c00b141dc508.png)

**Comment by Sennevds** [comment]
I've just fixed this issue. Did you update to the latest version?

**Comment by Kobiash** [comment]
Sorry for the way too late response.
I had just updated the version and the problem solved.

Thank you.

**Comment by Kobiash** [comment]
Immediate response by the owner and very slow one by the reporter :-)
