### ISSUE TITLE
Unit system_sensor.service has a bad unit file setting.

### ISSUE THREAD

**Issue by ezraholm50** [Sennevds/system_sensors#13]
Hello i've setup as the instructions and changed the home dir to /home/dietpi.

But i get this error, please advise.
Thanks

```
dietpi@virtualhereserver:~/system_sensors$ sudo systemctl start system_sensor.service
Failed to start system_sensor.service: Unit system_sensor.service has a bad unit file setting.
See system logs and 'systemctl status system_sensor.service' for details.
dietpi@virtualhereserver:~/system_sensors$ systemctl status system_sensor.service
● system_sensor.service - System Sensor service
   Loaded: bad-setting (Reason: Unit system_sensor.service has a bad unit file setting.)
   Active: inactive (dead)
```

**Comment by codeclinic** [comment]
You need to edit the settings.yaml file and change `=[user]` to your system username. If you are on a Raspi this will most likely be the pi user. So you should change it accordingly eg: `=pi`

>

**Comment by ezraholm50** [comment]
I have this setup like `=[user]` on 2 other rpi zero's and it just works, should dynamically take the user who runs it right? Thanks

**Comment by Sennevds** [comment]
No you should change the [user] to the current user(or the user that has all the packages installed)

**Comment by mcfrojd** [comment]
Are you shure that it is the settings.yaml file that need change?
Not the "/etc/systemd/system/system_sensor.service" that should change?

In the settings.yaml file the only "user" part is the mqtt user right?
But the file "/etc/systemd/system/system_sensor.service" have a User=[user] part.

**Comment by mcfrojd** [comment]
User=[user] works fine on my raspberry pi 3 but not on my raspberry 4

I tried these to with no luck.
 User=[pi]
 User=[root]

**Comment by Sennevds** [comment]
Without the brackets

**Comment by mcfrojd** [comment]
That worked :-)
