### ISSUE TITLE
Unable to Install / possible problem with python 3.10.x

### ISSUE THREAD

**Issue by raviwarrier** [Sennevds/system_sensors#136]
Tried installing after reinstalling my rpi4-64 and got the following error:

https://pastebin.com/SBLTerXy

I see a lot of references to python 3.9, but I just installed 3.10.x. Is there a way to make it work with 3.10 or do I need to install 3.9.

Please help. Cheers.

**Comment by raviwarrier** [comment]
I don't remember installing it specifically, nor do I remember doing it in the past. does it not get installed with python? if not, should I install it and how?

**Comment by raviwarrier** [comment]
I installed python3-dev and it worked. thanks for pointing in that direction.

Just a question before I close the ticket: is this a new requirement coz as I mentioned I don't remember ever installing python3-dev separately before? If yes, you might want to update the readme, else at least put in an FAQ for the error...

Thanks again. have a great day. closing the ticket.

**Comment by Sennevds** [comment]
I haven't changed anything. I just looked at the error and googled it. Maybe it has something to do with using it in Arch

**Comment by raviwarrier** [comment]
Possible. Just changed to 64bit version of the OS. Thanks again.

**Comment by raviwarrier** [comment]
Possible. Just changed to 64bit version of the OS. Thanks again.
