### ISSUE TITLE
Power Status Alternative Value

### ISSUE THREAD

**Issue by codeclinic** [Sennevds/system_sensors#14]
Could you possibly give the option to output power status as values rather than text. Unfortunately, when you have a pi that hates all power supplies it's near impossible to find a card layout where the throttled power status displays nicely. EG:

> The Raspberry Pi is throttled due to a bad power supply this can lead to corruption and instability, please replace your changer and cables.

If you could give the option for power status values in alignment with the HACS installable '[Raspberry Pi Power Supply Checker](https://github.com/custom-components/sensor.rpi_power)' package that would be great. It'd mean that local and remote servers can be monitored & reported with the same values regardless of the packages used.

**Comment by Sennevds** [comment]
I've updated the script to use a config file now. I will update it to have a value if you want text or the number.

**Comment by codeclinic** [comment]
Great. Thanks.
