### ISSUE TITLE
Will this work on regular Debian Linux X64

### ISSUE THREAD

**Issue by ranrinc** [Sennevds/system_sensors#140]
Will the script work for regular PC running Debian Linux?

**Comment by haxorjim** [comment]
Worked for me...

git clone ...

pipenv install -r requirements.txt

(configure it)

pipenv run python src/system_sensors.py src/settings.yaml

**Comment by ranrinc** [comment]
> Worked for me...
> 
> git clone ...
> 
> pipenv install -r requirements.txt
> 
> (configure it)
> 
> pipenv run python src/system_sensors.py src/settings.yaml

thanks man... will try it on my machine
