### ISSUE TITLE
Reason for load_x is shown as fraction as it prints as "processes"

### ISSUE THREAD

**Issue by mmattel** [Sennevds/system_sensors#148]
I can not believe that the processes shown is a fraction and lower than 0.
Imho this should be fractionless and > 0

![image](https://user-images.githubusercontent.com/3321281/208423934-44ebee49-81b0-4b61-8620-5520e6cb6416.png)

**Comment by Sennevds** [comment]
You can always create a PR to fix this

**Comment by mmattel** [comment]
ok, got it 😅
