### ISSUE TITLE
Feature request - Add client_id

### ISSUE THREAD

**Issue by OneAmongMany84** [Sennevds/system_sensors#15]
Hi 

I'm in the process of setting this up. My MQTT broker allows connections based on client-id prefix. Could you please add 'client_id' as a possible field for the settings file. I've added the yaml in mine and have the service running, but I don't think it can connect (broker shows only 2 clients still (HA and the MQTT browser)).

Really impressed by this project!

Alex

**Comment by Sennevds** [comment]
I've included the client_id in the settings.yaml. This setting is mandatory!

**Comment by OneAmongMany84** [comment]
Awesome. Thank you. Will test tonight. To 'upgrade' do I just need to replace the settings.yaml and sensors.py?

**Comment by Sennevds** [comment]
Replace the sensors.py and just add client_id to the settings.yaml
