### ISSUE TITLE
Rpi4 support?

### ISSUE THREAD

**Issue by mcfrojd** [Sennevds/system_sensors#16]
I get this error when i run "sudo systemctl start system_sensor.service"

Error:
Failed to start system_sensor.service: Unit system_sensor.service has a bad unit file setting.
See system logs and 'systemctl status system_sensor.service' for details.

Details:
● system_sensor.service - System Sensor service
   Loaded: bad-setting (Reason: Unit system_sensor.service has a bad unit file setting.)
   Active: inactive (dead)

jan 20 19:15:17 Rpi4 systemd[1]: /etc/systemd/system/system_sensor.service:5: Invalid user/group name or numeric ID: [user]

I get no error on my rpi3

**Comment by codeclinic** [comment]
You've not edited your settings.yaml correctly. See: #13

**Comment by Sennevds** [comment]
Thank you @codeclinic
