### ISSUE TITLE
WiFi Signal Strength

### ISSUE THREAD

**Issue by codeclinic** [Sennevds/system_sensors#17]
I'd find it really useful if you could add wifi strength as a sensor.

The key metrics would be signal strength and connection speed.

Thanks.

**Comment by Sennevds** [comment]
If you could find a way to add this metrics I will add them

**Comment by gieljnssns** [comment]
I use this in node-red
```
cat /proc/net/wireless | grep wlan0: | awk '{print int($4)}'
```

**Comment by Sennevds** [comment]
Perfect will add it!

**Comment by Sennevds** [comment]
Updated the repo

**Comment by codeclinic** [comment]
Any chance you could also add in an option for Lan speed?

One way to do this is with `cat /sys/class/net/eth0/speed`
