### ISSUE TITLE
Callback API version 1 is deprecated

### ISSUE THREAD

**Issue by xaquib666** [Sennevds/system_sensors#179]
Hello,

Callback API version 1 is deprecated. Can anyone help me to fix this issue?

![image](https://github.com/user-attachments/assets/48ebcc46-8047-45fa-92f0-26ea212ecb6c)

Thanks!

**Comment by TheRealFalseReality** [comment]
Same here

**Comment by Mattiasselander** [comment]
same

**Comment by Mattiasselander** [comment]
<img width="832" alt="Skärmavbild 2024-08-13 kl  23 00 49" src="https://github.com/user-attachments/assets/4b32bc42-dfce-4354-9b0e-9465e6853368">

**Comment by KayGundhardt** [comment]
Hi folks,

same here :((

@Mattias Thanks for your comment although I am not sure what it means...?
:)

**Comment by Mattiasselander** [comment]
it is no longer working with the update of poha as i understand. but it is integraded in HA now with https://www.home-assistant.io/integrations/systemmonitor/

**Comment by KayGundhardt** [comment]
Not really :( Your tool could handle an external MQTT client to be connected to HA... No way to repair this? ;(

**Comment by Mattiasselander** [comment]
i have no ide how to code, but i think if u could install paho 1.6.1 instedd of 2.x
then maybe it will work. 

the owner of the script maybe have a solution to update it for 2.0

**Comment by KayGundhardt** [comment]
Oh man - how stupid :D 

I could have thought of that myself ... ;))

Now it connects and publishes the topics, but sadly no measured values:

<img width="524" alt="Bildschirmfoto 2024-08-15 um 09 50 26" src="https://github.com/user-attachments/assets/4fcd5b92-cabe-4b39-a86a-ae63bec343fb">

**Comment by Mattiasselander** [comment]
i dont understand why u dont use the integraded one ![image](https://github.com/user-attachments/assets/5bdde9fe-b539-490e-8d65-85982716f892)

**Comment by KayGundhardt** [comment]
Because I want to remotely monitor ANOTHER raspberry pis system over network, so NOT the HomeAssistant Host!Am 17.08.2024 um 20:46 schrieb Mattiasselander ***@***.***>:﻿
i dont understand why u dont use the integraded one 5675A38A-3DB0-4A5C-9341-BEE3005D6A72.jpeg (view on web)

**Comment by Mattiasselander** [comment]
oh i understand !
then i don't know..

**Comment by KayGundhardt** [comment]
Anyone else maybe?With old Pago version I get connected to the MQTT broker and topics are published but according values are not… Any idea anyone?Help would be highly appreciated -thank you!!Am 17.08.2024 um 20:59 schrieb Mattiasselander ***@***.***>:﻿
oh i understand !
then i don't know..

**Comment by Mattiasselander** [comment]
try to remove the power sensor, have read alot about that

**Comment by KayGundhardt** [comment]
Like this?

```
  temperature: true
  display: true
  clock_speed: true
  fan_speed: true
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: "enp1s0" # true for all interfaces, otherwise the name of the interface
  net_rx: true # true for all interfaces, otherwise the name of the interface
  swap_usage: true
  power_status: false
  last_boot: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
  wifi_strength: false
  wifi_ssid: false
```

Unfortunately it did not help :(

**Comment by Mattiasselander** [comment]
u get some logs on that?

**Comment by KayGundhardt** [comment]
No, unfortunately not: I'm still a complete noob… :)) But if you tell me how, I will gladly try to read out a log!

**Comment by Mattiasselander** [comment]
i am a noob to my friend :) 

are u geting some error in settings>system>logs

**Comment by KayGundhardt** [comment]
No, this is all I can find about it in the logs:

```
2024-08-17T22:21:58: 	system-sensors/sensor/geppetto-cam/availability (QoS 0)
2024-08-17T22:21:58: 14TfyeRtj4zuhSjSYamPeQ 0 system-sensors/sensor/geppetto-cam/availability
2024-08-17T22:21:58: 	system-sensors/sensor/geppetto-cam/state (QoS 0)
2024-08-17T22:21:58: 14TfyeRtj4zuhSjSYamPeQ 0 system-sensors/sensor/geppetto-cam/state
```

**Comment by Mattiasselander** [comment]
i think this github i dead and i can't help u more.. u are on your on now..

**Comment by KayGundhardt** [comment]
Okay, thanks anyway.

If anyone else could help: help would be really appreciated  
:)

**Comment by TheRealFalseReality** [comment]
Try installing glances if you can, it may not be as easy, but try using Docker, then use the HA integration for Glances to get it in your instance. However, I wanted to install this for a more lightweight component rather than glances, I like this repository but cannot install on anything else, for now.

**Comment by Sennevds** [comment]
Sorry all for the late response.
I don't use this script as much anymore but I will try to update is

**Comment by Sennevds** [comment]
I've fixed it in the latest source.( btw this was only a warning the code worked without my changes so if you didn't receive any values in home assistant there was something else wrong)

**Comment by KayGundhardt** [comment]
Okay, thank you for the update! :) But if I can’t see any values (although the topics themselves are visible) on the broker, then it’s the client that either don’t get‘s the values from the system itself or does not publish them, right? Could you somehow tell me how I could get to a log that could help?

**Comment by Sennevds** [comment]
Could you open a new ticket with the logs your config and a screenshot of a mqtt client with the messages?

**Comment by KayGundhardt** [comment]
Okay, sure - thank you!Config and MQTT-Data are no problem. But where can I get the logs you need?Am 23.08.2024 um 15:45 schrieb Senne ***@***.***>:﻿
Could you open a new ticket with the logs your config and a screenshot of a mqtt client with the messages?
