### ISSUE TITLE
system_sensor.service doesn't work

### ISSUE THREAD

**Issue by mihai-catalin** [Sennevds/system_sensors#20]
Hello,
I'm trying to monitor a RPi running OSMC with this script.
If i am running the script from command line (the same as from system_sensor.service) it is working.
Here is the content of system_sensor.service:
`[Unit]
Description=System Sensor service
After=network.target

[Service]
User=osmc
Type=idle
ExecStart=/usr/bin/python3 /home/osmc/system_sensors/src/system_sensors.py /home/osmc/system_sensors/src/settings.yaml

[Install]
WantedBy=multi-user.target
`

**Comment by Sennevds** [comment]
Does it work if you run systemctl start system-sensor.service? What is the output off systemctl status system-sensor.service?

**Comment by mihai-catalin** [comment]
Sorry,  I forgot to mention this info. The service appear successfully started. I will add a screenshot later in the evening.

**Comment by mihai-catalin** [comment]
Here is the status of the service. I started to believe maybe is something related to OSMC linux. I searched but didn't find something close.
`
osmc@osmc:~$ sudo systemctl status system-sensors.service
* system-sensors.service - System Sensor service
   Loaded: loaded (/etc/systemd/system/system-sensors.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-02-12 23:24:56 EET; 5min ago
 Main PID: 1962 (python3)
   CGroup: /system.slice/system-sensors.service
           `-1962 /usr/bin/python3 /home/osmc/system_sensors/src/system_sensors.py /home/osmc/system_sensors/src/settings.yaml

Feb 12 23:24:56 osmc systemd[1]: Started System Sensor service.
`

**Comment by RubenDijk** [comment]
this is my error output when i want to start the system_sensor.service

● system_sensor.service - System Sensor service
   Loaded: bad-setting (Reason: Unit system_sensor.service has a bad unit file setting.)
   Active: inactive (dead)

Feb 14 19:56:02 RaspberryPi4 systemd[1]: /etc/systemd/system/system_sensor.service:5: Invalid user/group name or numeric ID: [user]

**Comment by codeclinic** [comment]
Did you take a look here: https://github.com/Sennevds/system_sensors/issues/16

**Comment by RubenDijk** [comment]
@codeclinic Sorry my bad, #16 solve my problem. thanks for the fast respone

**Comment by mihai-catalin** [comment]
Finally was solved with the help from OSMC forum.
In case someone else will face the same problem have a look at https://discourse.osmc.tv/t/systemd-service-doesnt-work-corectly/84328/10
