### ISSUE TITLE
MQTT Broker cannot interpret the data

### ISSUE THREAD

**Issue by dkalinai** [Sennevds/system_sensors#23]
Any idea what this is? I am trying to connect two raspberries as in your guide, one I did perfectly, the other one almost copy pasted just changed client names etc.

Home assistant is giving me this:

`Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'name': 'motionpiPowerStatus', 'state_topic': 'system-sensors/sensor/motionpi/state', 'value_template': '{{ value_json.power_status}}', 'unique_id': 'motionpi_sensor_power_status', 'device': {'identifiers': ['motionpi_sensor'], 'name': 'motionpiSensors', 'model': 'RPI motionpi', 'manufacturer': 'RPI', 'icon': 'mdi:power-plug'}, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 81, in async_discover_sensor
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['device']['icon']`

The only data that comes through is the wifi signal number.

**Comment by dkalinai** [comment]
This commit broke it, checking out an earlier commit addresses the issue: https://github.com/Sennevds/system_sensors/commit/9218a1f30b7df18a2ad12b0500e2bfdd873a7fd3

**Comment by dkalinai** [comment]
I suggest you revert this. Reason wifi signal works is because nobody added an icon to this.

**Comment by Poeschl** [comment]
Will be fixed with #24.

**Comment by Sennevds** [comment]
@dkalinai I've merged the pull request of Poeschl could you check if it works now?
I'm currently not at home so I can't test

**Comment by Poeschl** [comment]
![image](https://user-images.githubusercontent.com/5469257/76063118-5f297e80-5f87-11ea-9cd5-8c26c32ce3f3.png)
![image](https://user-images.githubusercontent.com/5469257/76063241-a0ba2980-5f87-11ea-9fce-8cbe0c869aad.png)

**Comment by dkalinai** [comment]
Sorry, this does work fine and can be closed.
