### ISSUE TITLE
Does not reconnect if MQTT server connection lost

### ISSUE THREAD

**Issue by tt1pjm** [Sennevds/system_sensors#29]
Need to restart service anytime connection to MQTT is lost.

**Comment by Sennevds** [comment]
Hmm weird. I will look into it but I use: loop_forever normally this reconnects automatically

> client.loop_forever() will block, processing the network traffic and reconnecting automatically as necessary.

**Comment by Sennevds** [comment]
@tt1pjm is this still the case?

**Comment by Sennevds** [comment]
Closing this issue because of no response. If it's still a problem reopen this issue!
