### ISSUE TITLE
FR: Upgrade(s) Available Sensor

### ISSUE THREAD

**Issue by codeclinic** [Sennevds/system_sensors#30]
Would it be possible to add some sort of indicator as to whether the system OS has available updates?

This way we'd know when a server needs us to ssh in and perform an upgrade. You can get this info from the cli using the methods mentioned here: (https://unix.stackexchange.com/questions/19470/list-available-updates-but-do-not-install-them)

**Comment by Sennevds** [comment]
Hhm looks interesting. I will try to look into in it this weekend

**Comment by codeclinic** [comment]
I momentarily forgot that this was written in python. So, I just had a quick look for anything python related and found this:
https://gist.github.com/yumminhuang/8b1502a49d8b20a6ae70

**Comment by codeclinic** [comment]
There is also a python-apt module which might be a better option:
import apt
cache=apt.Cache()
cache.update()
cache.open(None)
cache.upgrade()
for pkg in cache.getChanges():
    print pkg.sourcePackageName, pkg.isUpgradeable

See here for info: https://stackoverflow.com/questions/3092613/python-apt-get-list-upgrades

**Comment by Sennevds** [comment]
Do you only want a boolean that there are upgrades available or a number of the amount or a list of packages?

**Comment by Sennevds** [comment]
I've added the amount of upgrades available if you only want a boolean you always could create a template sensor
