### ISSUE TITLE
Publish releases

### ISSUE THREAD

**Issue by codeclinic** [Sennevds/system_sensors#33]
You're regularly pushing out updates with great new features, but having to manually check back for changes isn't always that easy when using dozens of Github projects. Would it be possible for you to publish releases?

That way its a simple process to see if we have the latest version or whether we need to upgrade.

Thanks.

**Comment by Sennevds** [comment]
I never did that with github. Will check it out!

**Comment by Sennevds** [comment]
Okay that wasn't hard release created!

**Comment by codeclinic** [comment]
Great. Thanks.
