### ISSUE TITLE
Invalid JSON?

### ISSUE THREAD

**Issue by Gertjuh** [Sennevds/system_sensors#34]
Hi,

Thanks for your work!
Tried to get it working today but no luck. MQTT data is received but could not extract the temperature. Many tries later I decided to check the message that I receive and checked that in a json format tool. This tool says it is invalid json. Maybe that is why it is not working for me?

![Invalid_Json](https://user-images.githubusercontent.com/33812880/80992643-1d5b6e00-8e3a-11ea-8fb7-3334ad2f0c4d.JPG)

**Comment by Sennevds** [comment]
Normally fixed in latest release! Could you check

**Comment by Sennevds** [comment]
@Gertjuh is it fixed for you?

**Comment by Sennevds** [comment]
Closing this issue after no response. Feel free to reopen this issue if it isn't fixed for you!
