### ISSUE TITLE
When HA server is restarted the clients no longer update

### ISSUE THREAD

**Issue by awooganl** [Sennevds/system_sensors#38]
Not sure if this is a bug in HA or in the system_sensors package, but when the HA server is restarted (due to upgrade or change to configuration), the system_sensors sensors remain Unavailable in HA until the MQTT Pi clients have their service restarted.

**Comment by Sennevds** [comment]
Could you try out with the latest source code?

**Comment by awooganl** [comment]
I've just installed the new source code and restarted it on one of my Pi's.  Then rebooted HA, but unfortunately, the Pi remained in Unavailable until I restarted the service again (gave it plenty of time in between).  The restart of the service was instant compared to a couple of minutes before, so it has improved one aspect, but not resolved the issue yet.  As soon as the service was restarted the HA reported it as Unknown and then after a minute or so to providing data again.

**Comment by Sennevds** [comment]
I've just updated the code. I've tested with a hass restart and a mqtt server restart and for me it looks like it works.

**Comment by awooganl** [comment]
Have again updated to your committed version, but it made no difference.  HA reports the client as Unavailable until it is restarted.

The only difference is that the client does report a connected to broker event in systemctl (before restart)

`quinten@serverpi:~/system_sensors/src $ sudo systemctl status system_sensor
● system_sensor.service - System Sensor service
   Loaded: loaded (/etc/systemd/system/system_sensor.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-06-25 09:48:29 BST; 22min ago
 Main PID: 28032 (python3)
    Tasks: 3 (limit: 4915)
   Memory: 10.5M
   CGroup: /system.slice/system_sensor.service
           └─28032 /usr/bin/python3 /home/quinten/system_sensors/src/system_sensors.py /home/quinten/system_sensors/src/settings.yaml

Jun 25 09:48:29 serverpi systemd[1]: Started System Sensor service.
Jun 25 09:48:29 serverpi python3[28032]: send config message
Jun 25 09:48:30 serverpi python3[28032]: Connected to broker
Jun 25 09:56:51 serverpi python3[28032]: Connected to broker
`

**Comment by Sennevds** [comment]
A few things:

1. are you restarting your whole system or only hass?
2. Could you connect with a mqtt client and check if there are any incomming messages after restart
3. Do the topics homeassistant/sensor/device_name/ (temp, diskuse etc) exists?

**Comment by awooganl** [comment]
I'm restarting the whole system, as that's what generally happens when HA is updated to a new version from the Supervisor.

I'm no MQTT expert (I have very little knowledge of it) so could you explain a little more with what you mean by connecting a mqtt client ?  This should be a different client to the one on the Pi?  Any suggestions what client I should be using?  The same for the last question, where do you want me to check for the topics?  On the HA server, or on the Pi client?

**Comment by Sennevds** [comment]
for windows you got mqtt-explorer with this software you can connect to your broker and see all incomming messages

**Comment by awooganl** [comment]
Ah great, I see they do an OSX version too, so when I finish work today I'll give that a go

**Comment by awooganl** [comment]
I can't test for question 2 yet as I'm printing something with Octoprint (also runs on HA), but this should answer question 3:

<img width="638" alt="Screenshot 2020-06-25 at 19 46 41" src="https://user-images.githubusercontent.com/51190401/85780801-ea887480-b71c-11ea-9e8f-0e24adb4ca9d.png">

Serverpi runs the latest .py script, whereas Phonepi still runs the original version.

**Comment by tomlut** [comment]
> I'm restarting the whole system, as that's what generally happens when HA is updated to a new version from the Supervisor.

That is not what happens. Only the home assistant container(s) restart. Addons like MQTT keep running in their own containers. You can stop home assistant and the broker will keep running (though if you use a home assistant user for authentication that will fail).

I have not rebooted my home assistant host for over 6 months. Restarting or upgrading home assistant does make the sensors unavailable until they next update (60sec I think) but there is no need to restart the remote clients. 

Setting the integration to publish retained messages would prevent the unavailable state at HA restart since as soon as home assistant starts all topics it is subscribed to will receive an update.

**Comment by awooganl** [comment]
Sounds like you run HA through a different means than I do, as I'm seeing the same behaviour when

Restarting through the Supervisor (which reboots the RPi)

<img width="407" alt="Screenshot 2020-06-27 at 10 26 44" src="https://user-images.githubusercontent.com/51190401/85919167-dbaada80-b860-11ea-8363-2e516b4429c7.png">

or restarting through the Configuration (which afaik only restarts HA and not the Add-Ons)

<img width="634" alt="Screenshot 2020-06-27 at 10 27 08" src="https://user-images.githubusercontent.com/51190401/85919206-45c37f80-b861-11ea-80fc-f5eaccb29478.png">

Is your MQTT broker an Add-On

<img width="840" alt="Screenshot 2020-06-27 at 10 32 28" src="https://user-images.githubusercontent.com/51190401/85919264-ac489d80-b861-11ea-951c-e2458076e58f.png">

 or a HA module?

<img width="880" alt="Screenshot 2020-06-27 at 10 33 14" src="https://user-images.githubusercontent.com/51190401/85919271-b4084200-b861-11ea-95ae-b1ec97f951ca.png">

I suspect the first?

**Comment by tomlut** [comment]
> Is your MQTT broker an Add-On

Yes. Hence it is in it's own container and unaffected by a home assistant restart.

**Comment by awooganl** [comment]
I'm going to give that a go then as well.  Sort of makes sense really, although I just followed the instructions on the readme which says that there is nothing to do if you have MQTT discovery enabled.

**Comment by awooganl** [comment]
Having now installed the MQTT Add-On, instead of the embedded MQTT broker, I'm pleased to report that the RPi clients survive both a complete reboot and just a HA server restart.  Maybe the instructions can be updated for other newbies, but as far as I'm concerned, this issue is now resolved.  Thanks!
