### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by svh1985** [Sennevds/system_sensors#42]
Hi!

Did you ever consider making a docker-image? A lot of people, myself included, rather not install software on the OS and use Docker images. Looking at the steps to install I don't think it should be that hard.

Thanks!

**Comment by Sennevds** [comment]
There's a guy who made a docker version of this: https://hub.docker.com/r/jan1993/system_sensors 23

**Comment by emkookmer** [comment]
@Sennevds The repository behind the docker hub version you're pointing at is outdated, the last commit is from Dec 2019.

https://github.com/jangottweiss/system_sensors

Please review PR #78
