### ISSUE TITLE
Allow script to run on Pi hardware running a non Pi-OS distro

### ISSUE THREAD

**Issue by MaxVRAM** [Sennevds/system_sensors#45]
Thanks a ton for the great script and guide. I've got this running on 4 x Pi Zeros running Rasperry Pi OS Lite and it works a treat.

I've got a couple of Pi 4s that are running Ubuntu Server. I thought this script could work on, but it doesn't seem to be the case. I had a squiz through your code and can't quite work out what aspect is stopping this from happening on that OS.

When I punch in `sudo systemctl status system_sensor.service` (so many s'), I get this:
```
● system_sensor.service - System Sensor service
     Loaded: loaded (/etc/systemd/system/system_sensor.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-07-16 21:21:32 AEST; 1h 6min ago
   Main PID: 143966 (python3)
      Tasks: 2 (limit: 4434)
     CGroup: /system.slice/system_sensor.service
             └─143966 /usr/bin/python3 /home/me/sensors/system_sensor.py /home/me/sensors/settings.yaml

Jul 16 21:22:32 ubuntu python3[143966]:     temp = check_output(["vcgencmd", "measure_temp"]).decode("UTF-8")
Jul 16 21:22:32 ubuntu python3[143966]:   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
Jul 16 21:22:32 ubuntu python3[143966]:     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
Jul 16 21:22:32 ubuntu python3[143966]:   File "/usr/lib/python3.8/subprocess.py", line 489, in run
Jul 16 21:22:32 ubuntu python3[143966]:     with Popen(*popenargs, **kwargs) as process:
Jul 16 21:22:32 ubuntu python3[143966]:   File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
Jul 16 21:22:32 ubuntu python3[143966]:     self._execute_child(args, executable, preexec_fn, close_fds,
Jul 16 21:22:32 ubuntu python3[143966]:   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
Jul 16 21:22:32 ubuntu python3[143966]:     raise child_exception_type(errno_num, err_msg, err_filename)
Jul 16 21:22:32 ubuntu python3[143966]: FileNotFoundError: [Errno 2] No such file or directory: 'vcgencmd'
```

Is it possible to run it on distros other than Raspberry Pi OS? I don't think it mentions it either way in the readme, so it would be good to clarify.

**Comment by Sennevds** [comment]
There are some rpi specific commands(like vcgencmd) that wont work on other systems.
Maybe in the feature I will make the script so it would work on other systems but for the moment I don't have any time for it sorry.

**Comment by MaxVRAM** [comment]
I'm totally new to Python, but keen to learn a little more. I'll have a dig around over the weekend and see if I can find any workarounds or replacements for broken commands.

**Comment by MaxVRAM** [comment]
Would be best to test this first. I have it sending temp data from Ubuntu Server 20.04, but I really took a stab in the dark, so not sure how stable or accurate this approach is.

**Comment by MaxVRAM** [comment]
The payload was showing inside Node-RED debug, but since my Pi wasn't using WiFi, the value for WiFi strength was empty, causing the entities in Home Assistant to fail. Added an `if not wifi_stregnth" to output a zero in such cases.

Script is now sending data correctly to my HA dashboard entities and has been stable for half an hour. Hope this solves the issue.
