### ISSUE TITLE
Feature Request - reboot/shutdown

### ISSUE THREAD

**Issue by snizzleorg** [Sennevds/system_sensors#5]
It would be great if one could add a reboot / shutdown switch

**Comment by codeclinic** [comment]
Is that possible without leaving the remote system open to malicious reboots, etc? Personally, I've setup remote ssh commands using [public-private key pairs](https://www.linuxtechi.com/execute-linux-commands-remote-system-over-ssh/) then created my own button to call the relevant shell_command in Home Assistant.

![FireShot Screen Capture #041 - 'Home Assistant' - hass-cck-1_duckdns_org_8123_lovelace_5](https://user-images.githubusercontent.com/6069510/72374390-7926ad80-370a-11ea-8207-f362f2726b6f.png)

**Comment by Sennevds** [comment]
This would be the safer option. Mqtt has basic authentication but is maybe not secure enough for shutdown en reboot command's.
I think this script has it's purpose to get some info but maybe it needs to be read-only.

**Comment by codeclinic** [comment]
I agree, MQTT has essentially no security and would just be asking for trouble. to implement this. It'd be nice to have but not worth the risk. Creating your own shell_command in combination with the link above is easy enough to do. You just need to remember to do the key pairing whilst in the Home Assistant venv if you are running it that way.
