### ISSUE TITLE
Can't get it running as a service

### ISSUE THREAD

**Issue by thomasgregg** [Sennevds/system_sensors#59]
Hi,

Thanks for the great work. I try to use your guide on how to install this as a service but whenever I reboot my Pi4 it doesn't come up.

If I manually start the service via sudo systemctl start system_sensors.service after the Pi is up it works fine. The error I can see when starting it automatically after a reboot is:

`pi@raspberrypi:~ $ journalctl -u system_sensors.service
-- Logs begin at Tue 2020-10-06 16:43:23 CEST, end at Tue 2020-10-06 16:44:20 CEST. --
Oct 06 16:43:34 raspberrypi systemd[1]: Started System Sensor service.
Oct 06 16:43:34 raspberrypi python3[777]: Traceback (most recent call last):
Oct 06 16:43:34 raspberrypi python3[777]:   File "/home/pi/system_sensors/src/system_sensors.py", line 416, in <module>
Oct 06 16:43:34 raspberrypi python3[777]:     mqttClient.connect(settings["mqtt"]["hostname"], settings["mqtt"]["port"])
Oct 06 16:43:34 raspberrypi python3[777]:   File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, 
Oct 06 16:43:34 raspberrypi python3[777]:     return self.reconnect()
Oct 06 16:43:34 raspberrypi python3[777]:   File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071,
Oct 06 16:43:34 raspberrypi python3[777]:     sock = self._create_socket_connection()
Oct 06 16:43:34 raspberrypi python3[777]:   File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522,
Oct 06 16:43:34 raspberrypi python3[777]:     return socket.create_connection(addr, source_address=source, timeout=self._keepa
Oct 06 16:43:34 raspberrypi python3[777]:   File "/usr/lib/python3.7/socket.py", line 727, in create_connection
Oct 06 16:43:34 raspberrypi python3[777]:     raise err
Oct 06 16:43:34 raspberrypi python3[777]:   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
Oct 06 16:43:34 raspberrypi python3[777]:     sock.connect(sa)
Oct 06 16:43:34 raspberrypi python3[777]: OSError: [Errno 101] Network is unreachable
Oct 06 16:43:35 raspberrypi systemd[1]: system_sensors.service: Main process exited, code=exited, status=1/FAILURE
Oct 06 16:43:35 raspberrypi systemd[1]: system_sensors.service: Failed with result 'exit-code'.
`

![image](https://user-images.githubusercontent.com/2538782/95217573-a0229380-07f3-11eb-9353-4989a4318671.png)

Any help would be appreciated.

**Comment by Sennevds** [comment]
could you change the following line in the service file
After=multi-user.target
to
After=multi-user.target network-online.target
Wants=network-online.target

**Comment by thomasgregg** [comment]
Thanks so much. I think this in combination with this setting:

![image](https://user-images.githubusercontent.com/2538782/95234313-b0436e80-0805-11eb-9a79-bb208372ff31.png)

![image](https://user-images.githubusercontent.com/2538782/95234500-bc2f3080-0805-11eb-8cb7-81063726058c.png)

did the trick.
