### ISSUE TITLE
external_drives sensor fails because of Uppercase/lowercase issue

### ISSUE THREAD

**Issue by wittypluck** [Sennevds/system_sensors#72]
Hello,
the external_drives sensor fails if the name of the drive (not the path) contains an uppercase character, as is the case in the settings_example.yaml for example ("Drive1").

From a look in the code, it seems the drive name:
- keeps original case in the config message sensor name (system_sensors.py lines 528, 532 and 533)
- is forced to lower case in the payload sensor name (system_sensors.py line 124)
I think we should either lowercase everywhere or keep original case everywhere.

Thanks for the great script!

**Comment by Sennevds** [comment]
This should be lower case everywhere. I will fix it
