### ISSUE TITLE
Problem running latest release

### ISSUE THREAD

**Issue by sweichbr** [Sennevds/system_sensors#74]
Hi

I have used your script on many Pis I have with no issue.  I recently cloned the repo for a new install, and I am suddenly running in to some issues.

1. I get this error when running: 
```
File "system_sensors.py", line 96
    print (f"Message received: {message.payload.decode()}"  )
                                                         ^
SyntaxError: invalid syntax

```
2. It appears that 0.0.3 of rpi_bad_power is no longer valid, I was able to install 0.1.0 (not sure if this is related to the issue above.

**Comment by sweichbr** [comment]
I did just realize that the system I am trying to run it on is using python 3.5.3 and my last successful run was on 3.7.3

Could that be related?

Thanks

**Comment by Sennevds** [comment]
Rpi bad power requires at least python 3.6 https://github.com/Sennevds/system_sensors#system-requirements
