### ISSUE TITLE
How to include external drive

### ISSUE THREAD

**Issue by sfbuch** [Sennevds/system_sensors#75]
hi,

i have system sensors installed on a couple of rpis and it runs great - thanks for the effort!

there is only one minor issue: i can't include the external drive to show up in the stats. my external drive ist mounted under /media/storage/ but when i change to data in the config i does not show up.

do you have a clue to get this running?

**Comment by Sennevds** [comment]
Can you send me the config that's send to mqtt (homeassistant/sensor/{device name}/disk_use{name of disk}) and also the resulting json that's send as value (system-sensors/sensor/{device name}/state)

**Comment by Sennevds** [comment]
Going to close this issue if you still have this issue reopen this with extra info
