### ISSUE TITLE
Service fails to start on RPi reboot

### ISSUE THREAD

**Issue by AABatteries** [Sennevds/system_sensors#76]
I;ve found an issue where the service won't start if the network is unreachable on boot (and that happens because it takes a few seconds before my RPi establishes it's wifi connection)

Here's the output from `systemctl status system_sensors.service`

```
● system_sensors.service - System Sensor service
   Loaded: loaded (/etc/systemd/system/system_sensors.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-01-11 01:06:46 GMT; 13h ago
  Process: 596 ExecStart=/usr/bin/python3 /home/pi/system_sensors/src/system_sensors.py /home/pi/system_sensors/src/sett
 Main PID: 596 (code=exited, status=1/FAILURE)

Jan 11 01:06:46 octopi python3[596]:     sock = self._create_socket_connection()
Jan 11 01:06:46 octopi python3[596]:   File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522
Jan 11 01:06:46 octopi python3[596]:     return socket.create_connection(addr, source_address=source, timeout=self._keep
Jan 11 01:06:46 octopi python3[596]:   File "/usr/lib/python3.7/socket.py", line 727, in create_connection
Jan 11 01:06:46 octopi python3[596]:     raise err
Jan 11 01:06:46 octopi python3[596]:   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
Jan 11 01:06:46 octopi python3[596]:     sock.connect(sa)
Jan 11 01:06:46 octopi python3[596]: OSError: [Errno 101] Network is unreachable
Jan 11 01:06:46 octopi systemd[1]: system_sensors.service: Main process exited, code=exited, status=1/FAILURE
Jan 11 01:06:46 octopi systemd[1]: system_sensors.service: Failed with result 'exit-code'.
```

If this is the issue (I'm not 100% sure), can you update the script to retry instead of quitting when network is unreachable? The expected action is to retry or wait+retry to connect. The script (and service) works great if I manually ssh into the Pi and restart the service (now that wifi connection is established)

Raspberry Pi 4B+, Octopi 0.17.0 image (Raspbian base with Octoprint)

Thank you!

**Comment by Sennevds** [comment]
Have a look at this: https://unix.stackexchange.com/questions/353179/why-isnt-my-systemd-service-waiting-for-the-network
You can edit the service file to let it wait until there's a network connection

**Comment by Sennevds** [comment]
Of you still have this issue you can reopen this issue but I'm going to close it for now

**Comment by AABatteries** [comment]
Thanks for the help. The issue isn't consistent, as it seems to start up properly from time to time. It works well on my older/slower Raspberry 3B+ which leads me to thinking that RPi 4 booting way faster causes this issue. Thanks for helping me resolve this, the above worked
