### ISSUE TITLE
Do I have to keep it connected? 

### ISSUE THREAD

**Issue by hamdanfadi** [Sennevds/system_sensors#83]
Hi there,
Do I have to keep this command "sudo python3 system_sensors.py settings_example.yaml" running? 
I can't use my system if this is the case!!!
This is what it is currently showing:
send config message
Connected to broker

Cheers,

**Comment by Sennevds** [comment]
Read the entire readme here on github. The optional part tells you how to create a service for the script so you can use it without manually running the command
