### ISSUE TITLE
Python Program to run

### ISSUE THREAD

**Issue by DotumZane** [Sennevds/system_sensors#93]
Every time I Try to run the program I get this error message, any help would be great!

usage: system_sensors.py [-h] settings
system_sensors.py: error: the following arguments are required: settings
Traceback (most recent call last):
  File "/home/pi/system_sensors/src/system_sensors.py", line 687, in <module>
    args = _parser().parse_args()
  File "/usr/lib/python3.7/argparse.py", line 1758, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1790, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 2025, in _parse_known_args
    ', '.join(required_actions))
  File "/usr/lib/python3.7/argparse.py", line 2510, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.7/argparse.py", line 2497, in exit
    _sys.exit(status)
SystemExit: 2
>>> 

This is my settings

mqtt:
  hostname: Homeassistant
  port: 1883
  user: ********
  password: ********
deviceName: pi
client_id: 1234
timezone: America/Los_Angeles
update_interval: 60 #Defaults to 60
check_wifi_strength: true
check_wifi_ssid: false
check_available_updates: true
external_drives:
  Drive1: /boot/

**Comment by lecocqe** [comment]
it sounds that you forget to mention the settings file in your command line.

in the "src" directory, type python3 system_sensors.py settings.yaml

good luck

**Comment by DotumZane** [comment]
I still get the get the error.

**Comment by Sennevds** [comment]
Sorry for the late reply what is the full command you enter and what is the error?

**Comment by MaxVRAM** [comment]
I've added a feature to automatically search for a `settings.yaml` in the directory that contains `system_sensors.py`, should the user not include an argument for it's location. A warning is posted to console if this happens.

Feature issue is here #101 and pull request is here #104
